// <auto-generated />
using System;
using IronLedger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IronLedger.Api.Migrations
{
    [DbContext(typeof(IronLedgerDbContext))]
    [Migration("20260716162544_AddMeetObjects")]
    partial class AddMeetObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IronLedger.Api.Models.Entities.Athlete", b =>
                {
                    b.Property<Guid>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BodyWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AthleteId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.Attempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNum")
                        .HasColumnType("int");

                    b.Property<int>("LiftType")
                        .HasColumnType("int");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("AttemptId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AthleteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BestBenchKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BestDeadliftKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BestSquatKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DotsScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EquipmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Federation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AthleteId");

                    b.ToTable("Leaderboard");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.Meet", b =>
                {
                    b.Property<Guid>("MeetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Federation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationClosesAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationOpensAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MeetId");

                    b.ToTable("Meets");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.MeetObjects.MeetDivision", b =>
                {
                    b.Property<Guid>("MeetDivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<string>("MeetDivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("MeetDivisionId");

                    b.HasIndex("MeetId");

                    b.ToTable("MeetDivisions");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.MeetObjects.MeetRegistration", b =>
                {
                    b.Property<Guid>("MeetRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BodyWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MeetDivisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetWeightClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MeetRegistrationId");

                    b.HasIndex("MeetDivisionId");

                    b.HasIndex("MeetId");

                    b.HasIndex("MeetWeightClassId");

                    b.ToTable("MeetRegistrations");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.MeetObjects.MeetWeightClass", b =>
                {
                    b.Property<Guid>("MeetWeightClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaximumWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MinimumWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("WeightClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetWeightClassId");

                    b.HasIndex("MeetId");

                    b.ToTable("MeetWeightClasses");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.MeetObjects.MeetDivision", b =>
                {
                    b.HasOne("IronLedger.Api.Models.Entities.Meet", null)
                        .WithMany("Divisions")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.MeetObjects.MeetRegistration", b =>
                {
                    b.HasOne("IronLedger.Api.Models.Entities.MeetObjects.MeetDivision", "MeetDivision")
                        .WithMany()
                        .HasForeignKey("MeetDivisionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IronLedger.Api.Models.Entities.Meet", null)
                        .WithMany("Registrations")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronLedger.Api.Models.Entities.MeetObjects.MeetWeightClass", "MeetWeightClass")
                        .WithMany()
                        .HasForeignKey("MeetWeightClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MeetDivision");

                    b.Navigation("MeetWeightClass");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.MeetObjects.MeetWeightClass", b =>
                {
                    b.HasOne("IronLedger.Api.Models.Entities.Meet", null)
                        .WithMany("WeightClasses")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.Meet", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Registrations");

                    b.Navigation("WeightClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
