// <auto-generated />
using System;
using IronLedger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IronLedger.Api.Migrations
{
    [DbContext(typeof(IronLedgerDbContext))]
    [Migration("20260709174613_LeaderboardUpdate1")]
    partial class LeaderboardUpdate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IronLedger.Api.Models.Entities.Athlete", b =>
                {
                    b.Property<Guid>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BodyWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AthleteId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.Attempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNum")
                        .HasColumnType("int");

                    b.Property<int>("LiftType")
                        .HasColumnType("int");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("AttemptId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("LeaderboardEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AthleteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BestBenchKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BestDeadliftKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BestSquatKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DotsScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EquipmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Federation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaderboardEntryId");

                    b.ToTable("Leaderboard");
                });

            modelBuilder.Entity("IronLedger.Api.Models.Entities.Meet", b =>
                {
                    b.Property<Guid>("MeetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Federation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetStatus")
                        .HasColumnType("int");

                    b.HasKey("MeetId");

                    b.ToTable("Meets");
                });
#pragma warning restore 612, 618
        }
    }
}
